import OpenAI from 'openai'

const config = useRuntimeConfig()
export const detectFraudPatterns = async (transactionData, customRules) => {
  const client = new OpenAI({
    apiKey: config.gemini,
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai/",
    defaultHeaders: {
      'Content-Type': 'application/json'
    }
  })
    const fraudExamples = [
        {
          "transaction_id": "TXN67890123456",
          "transaction_date": "2025-03-20T02:23:45",
          "transaction_amount": 75000.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "rajesh.kumar87@tempmail.com",
          "payer_mobile": "+91-9876543210",
          "payer_card_brand": "Visa",
          "payer_device": "d45tf67h8j9k0l",
          "payer_browser": "Chrome",
          "payee_id": "MERCHANT78901",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Suspicious transaction time (2:23 AM) with high amount (₹75,000)",
          "fraud_score": 0.89
        },
        {
          "transaction_id": "TXN56789012345",
          "transaction_date": "2025-03-21T15:12:33",
          "transaction_amount": 24999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "sunil.mehta77@disposable.com",
          "payer_mobile": "+91-8765432109",
          "payer_card_brand": null,
          "payer_device": "x67yz8901abc2",
          "payer_browser": "Safari",
          "payee_id": "MERCHANT45612",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Disposable email domain with mobile transaction",
          "fraud_score": 0.83
        },
        {
          "transaction_id": "TXN45678901234",
          "transaction_date": "2025-03-19T22:45:12",
          "transaction_amount": 35000.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "SBI",
          "payer_email": "priya.sharma56@gmail.com",
          "payer_mobile": "+91-7654321098",
          "payer_card_brand": null,
          "payer_device": "g34hi5j67k89l",
          "payer_browser": "Firefox",
          "payee_id": "MERCHANT23789",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Late night NEFT transaction with high value amount",
          "fraud_score": 0.86
        },
        {
          "transaction_id": "TXN34567890123",
          "transaction_date": "2025-03-18T16:33:56",
          "transaction_amount": 12999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "amit.patel22@gmail.com",
          "payer_mobile": "+91-6543210987",
          "payer_card_brand": "Mastercard",
          "payer_device": "p90qr1s23t45u",
          "payer_browser": null,
          "payee_id": "MERCHANT12378",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Card payment on mobile without browser information",
          "fraud_score": 0.78
        },
        {
          "transaction_id": "TXN23456789012",
          "transaction_date": "2025-03-17T10:19:27",
          "transaction_amount": 52999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "neha.gupta34@outlook.com",
          "payer_mobile": "+91-5432109876",
          "payer_card_brand": null,
          "payer_device": "v67wx8y90z12a",
          "payer_browser": "Edge",
          "payee_id": "MERCHANT56123",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Unusual high-value UPI transaction via web browser",
          "fraud_score": 0.92
        },
        {
          "transaction_id": "TXN12345678901",
          "transaction_date": "2025-03-16T03:45:15",
          "transaction_amount": 42000.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "vikram.singh45@gmail.com",
          "payer_mobile": "+91-4321098765",
          "payer_card_brand": null,
          "payer_device": "b34cd5e67f89g",
          "payer_browser": null,
          "payee_id": "MERCHANT89012",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Early morning NEFT transaction from mobile device",
          "fraud_score": 0.85
        },
        {
          "transaction_id": "TXN98765432109",
          "transaction_date": "2025-03-15T19:27:38",
          "transaction_amount": 15699.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "kavita.reddy77@ymail.com",
          "payer_mobile": "+91-3210987654",
          "payer_card_brand": "RuPay",
          "payer_device": "h12ij3k45l67m",
          "payer_browser": "Chrome",
          "payee_id": "MERCHANT34567",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Rarely used card brand (RuPay) with uncommon email domain",
          "fraud_score": 0.76
        },
        {
          "transaction_id": "TXN87654321098",
          "transaction_date": "2025-03-14T12:15:59",
          "transaction_amount": 86999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "rohit.verma23@gmail.com",
          "payer_mobile": "+91-2109876543",
          "payer_card_brand": null,
          "payer_device": "n90op1q23r45s",
          "payer_browser": null,
          "payee_id": "MERCHANT67890",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Extremely high UPI transaction amount via mobile",
          "fraud_score": 0.95
        },
        {
          "transaction_id": "TXN76543210987",
          "transaction_date": "2025-03-13T21:56:41",
          "transaction_amount": 51299.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "SBI",
          "payer_email": "ananya.joshi56@hotmail.com",
          "payer_mobile": "+91-1098765432",
          "payer_card_brand": "Visa",
          "payer_device": "t67uv8w90x12y",
          "payer_browser": "Firefox",
          "payee_id": "MERCHANT23456",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Evening high-value card transaction with rarely used email provider",
          "fraud_score": 0.81
        },
        {
          "transaction_id": "TXN65432109876",
          "transaction_date": "2025-03-12T14:32:27",
          "transaction_amount": 67500.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "rahul.sharma34@gmail.com",
          "payer_mobile": "+91-9087654321",
          "payer_card_brand": null,
          "payer_device": "z12ab3c45d67e",
          "payer_browser": null,
          "payee_id": "MERCHANT78345",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "UPI transaction amount exceeds typical mobile limit",
          "fraud_score": 0.93
        },
        {
          "transaction_id": "TXN54321098765",
          "transaction_date": "2025-03-11T09:11:18",
          "transaction_amount": 32000.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "divya.patel67@protonmail.com",
          "payer_mobile": "+91-8976543210",
          "payer_card_brand": null,
          "payer_device": "f89gh0i12j34k",
          "payer_browser": "Chrome",
          "payee_id": "MERCHANT45698",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Private email domain (protonmail) with high-value transaction",
          "fraud_score": 0.84
        },
        {
          "transaction_id": "TXN43210987654",
          "transaction_date": "2025-03-10T23:45:09",
          "transaction_amount": 47999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "karan.malhotra44@gmail.com",
          "payer_mobile": "+91-7865432109",
          "payer_card_brand": "Mastercard",
          "payer_device": "l56mn7o89p01q",
          "payer_browser": null,
          "payee_id": "MERCHANT12789",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Late night card transaction from mobile device",
          "fraud_score": 0.88
        },
        {
          "transaction_id": "TXN32109876543",
          "transaction_date": "2025-03-09T14:18:33",
          "transaction_amount": 95699.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "pooja.agarwal28@yahoo.com",
          "payer_mobile": "+91-6754321098",
          "payer_card_brand": null,
          "payer_device": "r23st4u56v78w",
          "payer_browser": "Safari",
          "payee_id": "MERCHANT56234",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "UPI transaction amount (₹95,699) significantly exceeds typical limits",
          "fraud_score": 0.97
        },
        {
          "transaction_id": "TXN21098765432",
          "transaction_date": "2025-03-08T11:26:54",
          "transaction_amount": 63500.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "arjun.mehta39@outlook.com",
          "payer_mobile": "+91-5643210987",
          "payer_card_brand": null,
          "payer_device": "x90yz1a23b45c",
          "payer_browser": null,
          "payee_id": "MERCHANT89123",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "High-value NEFT transaction from mobile device",
          "fraud_score": 0.87
        },
        {
          "transaction_id": "TXN10987654321",
          "transaction_date": "2025-03-07T15:43:22",
          "transaction_amount": 29900.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "SBI",
          "payer_email": "shreya.desai65@mailinator.com",
          "payer_mobile": "+91-4532109876",
          "payer_card_brand": "RuPay",
          "payer_device": "d67ef8g90h12i",
          "payer_browser": "Edge",
          "payee_id": "MERCHANT34789",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Disposable email domain with card payment",
          "fraud_score": 0.82
        },
        {
          "transaction_id": "TXN09876543210",
          "transaction_date": "2025-03-06T02:37:49",
          "transaction_amount": 17499.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "varun.khanna27@gmail.com",
          "payer_mobile": "+91-3421098765",
          "payer_card_brand": null,
          "payer_device": "j34kl5m67n89o",
          "payer_browser": null,
          "payee_id": "MERCHANT67345",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Early morning (2:37 AM) mobile UPI transaction",
          "fraud_score": 0.80
        },
        {
          "transaction_id": "TXN98765410987",
          "transaction_date": "2025-03-05T20:14:08",
          "transaction_amount": 38500.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "meera.shah43@tutanota.com",
          "payer_mobile": "+91-2310987654",
          "payer_card_brand": null,
          "payer_device": "p01qr2s34t56u",
          "payer_browser": "Chrome",
          "payee_id": "MERCHANT23890",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Private email service with high-value NEFT transaction",
          "fraud_score": 0.85
        },
        {
          "transaction_id": "TXN87654109876",
          "transaction_date": "2025-03-04T01:29:36",
          "transaction_amount": 22500.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "aarav.kapoor51@gmail.com",
          "payer_mobile": "+91-1209876543",
          "payer_card_brand": "Visa",
          "payer_device": "v78wx9y01z23a",
          "payer_browser": null,
          "payee_id": "MERCHANT45789",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Late night (1:29 AM) card transaction from mobile",
          "fraud_score": 0.83
        },
        {
          "transaction_id": "TXN76543098765",
          "transaction_date": "2025-03-03T18:51:22",
          "transaction_amount": 78999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "tanvi.sharma76@yahoo.com",
          "payer_mobile": "+91-9087612345",
          "payer_card_brand": null,
          "payer_device": "b45cd6e78f90g",
          "payer_browser": "Firefox",
          "payee_id": "MERCHANT12890",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "UPI transaction exceeding typical web platform limit",
          "fraud_score": 0.94
        },
        {
          "transaction_id": "TXN65432987654",
          "transaction_date": "2025-03-02T21:09:54",
          "transaction_amount": 23999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "nikhil.roy38@gmail.com",
          "payer_mobile": "+91-8976512340",
          "payer_card_brand": null,
          "payer_device": "h12ij3k45l67m",
          "payer_browser": null,
          "payee_id": "MERCHANT56789",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Evening NEFT transaction via mobile app",
          "fraud_score": 0.79
        },
        {
          "transaction_id": "TXN54321876543",
          "transaction_date": "2025-03-01T00:37:28",
          "transaction_amount": 57000.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "SBI",
          "payer_email": "aditi.mishra29@hotmail.com",
          "payer_mobile": "+91-7865123490",
          "payer_card_brand": "Mastercard",
          "payer_device": "n90op1q23r45s",
          "payer_browser": "Chrome",
          "payee_id": "MERCHANT89234",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Midnight (12:37 AM) high-value card transaction",
          "fraud_score": 0.91
        },
        {
          "transaction_id": "TXN43210765432",
          "transaction_date": "2025-02-28T18:22:16",
          "transaction_amount": 91500.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "rajiv.gupta47@gmail.com",
          "payer_mobile": "+91-6754123098",
          "payer_card_brand": null,
          "payer_device": "t67uv8w90x12y",
          "payer_browser": null,
          "payee_id": "MERCHANT34890",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Extremely high UPI amount (₹91,500) on mobile device",
          "fraud_score": 0.96
        },
        {
          "transaction_id": "TXN32109654321",
          "transaction_date": "2025-02-27T09:48:39",
          "transaction_amount": 31999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "manisha.tiwari62@protonmail.com",
          "payer_mobile": "+91-5643123098",
          "payer_card_brand": null,
          "payer_device": "z12ab3c45d67e",
          "payer_browser": "Safari",
          "payee_id": "MERCHANT67890",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Private email provider with high-value transaction",
          "fraud_score": 0.82
        },
        {
          "transaction_id": "TXN21098543210",
          "transaction_date": "2025-02-26T02:15:52",
          "transaction_amount": 69999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "ankit.singh84@gmail.com",
          "payer_mobile": "+91-4532187609",
          "payer_card_brand": "RuPay",
          "payer_device": "f89gh0i12j34k",
          "payer_browser": null,
          "payee_id": "MERCHANT12345",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Early morning (2:15 AM) large card transaction via mobile",
          "fraud_score": 0.93
        },
        {
          "transaction_id": "TXN10987432109",
          "transaction_date": "2025-02-25T22:24:47",
          "transaction_amount": 46999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "ishaan.sharma25@tempmail.io",
          "payer_mobile": "+91-3421658790",
          "payer_card_brand": null,
          "payer_device": "l56mn7o89p01q",
          "payer_browser": "Edge",
          "payee_id": "MERCHANT56901",
          "is_fraud": true,
          "fraud_source": "model",
          "fraud_reason": "Disposable email with high-value UPI web transaction",
          "fraud_score": 0.90
        }
      ]
    const nonFraudExamples = [
        {
          "transaction_id": "TXN98765432101",
          "transaction_date": "2025-03-15T09:23:45",
          "transaction_amount": 2499.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "rahul.sharma@gmail.com",
          "payer_mobile": "9876543210",
          "payer_card_brand": null,
          "payer_device": "SM-G973F",
          "payer_browser": "Chrome 121.0.6167.85",
          "payee_id": "MERCH78945612",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.07
        },
        {
          "transaction_id": "TXN98765432102",
          "transaction_date": "2025-03-16T14:45:12",
          "transaction_amount": 1250.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "SBI",
          "payer_email": "priya.patel@outlook.com",
          "payer_mobile": "8765432109",
          "payer_card_brand": null,
          "payer_device": "iPhone13,4",
          "payer_browser": null,
          "payee_id": "MERCH45678912",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.03
        },
        {
          "transaction_id": "TXN98765432103",
          "transaction_date": "2025-03-15T18:12:34",
          "transaction_amount": 8750.50,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "amit.singh@yahoo.com",
          "payer_mobile": "7654321098",
          "payer_card_brand": "Visa",
          "payer_device": "MacBookPro15,2",
          "payer_browser": "Safari 16.5",
          "payee_id": "MERCH12345678",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.12
        },
        {
          "transaction_id": "TXN98765432104",
          "transaction_date": "2025-03-17T11:32:56",
          "transaction_amount": 499.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "neha.gupta@gmail.com",
          "payer_mobile": "9876123450",
          "payer_card_brand": null,
          "payer_device": "Redmi Note 12",
          "payer_browser": null,
          "payee_id": "MERCH98761234",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.02
        },
        {
          "transaction_id": "TXN98765432105",
          "transaction_date": "2025-03-16T20:54:23",
          "transaction_amount": 12999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "vikram.desai@hotmail.com",
          "payer_mobile": "8765123490",
          "payer_card_brand": null,
          "payer_device": "HP-Pavilion-15",
          "payer_browser": "Firefox 111.0",
          "payee_id": "MERCH56789123",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.18
        },
        {
          "transaction_id": "TXN98765432106",
          "transaction_date": "2025-03-15T15:27:48",
          "transaction_amount": 3499.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "sanjay.mehta@gmail.com",
          "payer_mobile": "9812345670",
          "payer_card_brand": "Mastercard",
          "payer_device": "SM-A536E",
          "payer_browser": null,
          "payee_id": "MERCH34567891",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.05
        },
        {
          "transaction_id": "TXN98765432107",
          "transaction_date": "2025-03-17T08:12:56",
          "transaction_amount": 1099.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "pooja.sharma@gmail.com",
          "payer_mobile": "7612345890",
          "payer_card_brand": null,
          "payer_device": "Lenovo-Legion-5",
          "payer_browser": "Chrome 121.0.6167.85",
          "payee_id": "MERCH23456789",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.04
        },
        {
          "transaction_id": "TXN98765432108",
          "transaction_date": "2025-03-16T13:45:29",
          "transaction_amount": 5999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "SBI",
          "payer_email": "vivek.joshi@outlook.com",
          "payer_mobile": "9567123480",
          "payer_card_brand": "RuPay",
          "payer_device": "POCO X5",
          "payer_browser": null,
          "payee_id": "MERCH65432198",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.09
        },
        {
          "transaction_id": "TXN98765432109",
          "transaction_date": "2025-03-15T19:32:17",
          "transaction_amount": 799.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "ravi.kumar@yahoo.com",
          "payer_mobile": "8912345670",
          "payer_card_brand": null,
          "payer_device": "Dell-XPS-13",
          "payer_browser": "Edge 112.0.1722.39",
          "payee_id": "MERCH87654321",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.06
        },
        {
          "transaction_id": "TXN98765432110",
          "transaction_date": "2025-03-17T10:23:45",
          "transaction_amount": 24999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "ajay.verma@gmail.com",
          "payer_mobile": "9876234510",
          "payer_card_brand": null,
          "payer_device": "ASUS-Vivobook-15",
          "payer_browser": "Chrome 121.0.6167.85",
          "payee_id": "MERCH76543219",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.15
        },
        {
          "transaction_id": "TXN98765432111",
          "transaction_date": "2025-03-16T12:15:33",
          "transaction_amount": 1799.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "meera.singh@hotmail.com",
          "payer_mobile": "7123456890",
          "payer_card_brand": null,
          "payer_device": "OnePlus 11",
          "payer_browser": null,
          "payee_id": "MERCH54321987",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.03
        },
        {
          "transaction_id": "TXN98765432112",
          "transaction_date": "2025-03-15T22:43:21",
          "transaction_amount": 6499.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "deepak.sharma@gmail.com",
          "payer_mobile": "9234567810",
          "payer_card_brand": "Visa",
          "payer_device": "MacBookAir10,1",
          "payer_browser": "Safari 16.5",
          "payee_id": "MERCH43219876",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.11
        },
        {
          "transaction_id": "TXN98765432113",
          "transaction_date": "2025-03-17T14:28:56",
          "transaction_amount": 999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "shalini.mishra@gmail.com",
          "payer_mobile": "8765123409",
          "payer_card_brand": null,
          "payer_device": "Samsung A54",
          "payer_browser": null,
          "payee_id": "MERCH32198765",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.04
        },
        {
          "transaction_id": "TXN98765432114",
          "transaction_date": "2025-03-16T17:54:32",
          "transaction_amount": 3299.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "sunil.patel@outlook.com",
          "payer_mobile": "9634567810",
          "payer_card_brand": "Mastercard",
          "payer_device": "HP-Envy-x360",
          "payer_browser": "Chrome 121.0.6167.85",
          "payee_id": "MERCH21987654",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.08
        },
        {
          "transaction_id": "TXN98765432115",
          "transaction_date": "2025-03-15T16:37:48",
          "transaction_amount": 549.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "SBI",
          "payer_email": "ananya.das@gmail.com",
          "payer_mobile": "7698123450",
          "payer_card_brand": null,
          "payer_device": "Vivo V29",
          "payer_browser": null,
          "payee_id": "MERCH10987654",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.02
        },
        {
          "transaction_id": "TXN98765432116",
          "transaction_date": "2025-03-17T09:15:44",
          "transaction_amount": 15999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "rohit.malhotra@yahoo.com",
          "payer_mobile": "9345678120",
          "payer_card_brand": null,
          "payer_device": "Lenovo-ThinkPad-T14",
          "payer_browser": "Firefox 111.0",
          "payee_id": "MERCH09876543",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.17
        },
        {
          "transaction_id": "TXN98765432117",
          "transaction_date": "2025-03-16T21:28:15",
          "transaction_amount": 2199.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "nisha.reddy@gmail.com",
          "payer_mobile": "8123456790",
          "payer_card_brand": "RuPay",
          "payer_device": "Oppo Reno 8",
          "payer_browser": null,
          "payee_id": "MERCH98765430",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.07
        },
        {
          "transaction_id": "TXN98765432118",
          "transaction_date": "2025-03-15T13:49:33",
          "transaction_amount": 4999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "rajesh.gupta@hotmail.com",
          "payer_mobile": "9876543019",
          "payer_card_brand": null,
          "payer_device": "Acer-Aspire-5",
          "payer_browser": "Chrome 121.0.6167.85",
          "payee_id": "MERCH87654320",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.09
        },
        {
          "transaction_id": "TXN98765432119",
          "transaction_date": "2025-03-17T07:56:12",
          "transaction_amount": 699.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "sunita.shah@gmail.com",
          "payer_mobile": "7654321980",
          "payer_card_brand": null,
          "payer_device": "Xiaomi 13 Pro",
          "payer_browser": null,
          "payee_id": "MERCH76543210",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.03
        },
        {
          "transaction_id": "TXN98765432120",
          "transaction_date": "2025-03-16T16:35:27",
          "transaction_amount": 9999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "vikas.jain@outlook.com",
          "payer_mobile": "9123456780",
          "payer_card_brand": "Visa",
          "payer_device": "Dell-Inspiron-15",
          "payer_browser": "Edge 112.0.1722.39",
          "payee_id": "MERCH65432100",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.14
        },
        {
          "transaction_id": "TXN98765432121",
          "transaction_date": "2025-03-15T11:23:45",
          "transaction_amount": 1399.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "SBI",
          "payer_email": "anjali.tiwari@gmail.com",
          "payer_mobile": "8912345607",
          "payer_card_brand": null,
          "payer_device": "Realme GT Neo 3",
          "payer_browser": null,
          "payee_id": "MERCH54321000",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.04
        },
        {
          "transaction_id": "TXN98765432122",
          "transaction_date": "2025-03-17T19:47:52",
          "transaction_amount": 7999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "prakash.iyer@yahoo.com",
          "payer_mobile": "9567812340",
          "payer_card_brand": null,
          "payer_device": "MacBookPro16,2",
          "payer_browser": "Safari 16.5",
          "payee_id": "MERCH43210000",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.12
        },
        {
          "transaction_id": "TXN98765432123",
          "transaction_date": "2025-03-16T14:17:38",
          "transaction_amount": 899.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "divya.menon@gmail.com",
          "payer_mobile": "8765432901",
          "payer_card_brand": "Mastercard",
          "payer_device": "iQOO 9 Pro",
          "payer_browser": null,
          "payee_id": "MERCH32100000",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.05
        },
        {
          "transaction_id": "TXN98765432124",
          "transaction_date": "2025-03-15T20:34:16",
          "transaction_amount": 13499.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "karthik.nair@hotmail.com",
          "payer_mobile": "9876123450",
          "payer_card_brand": "Visa",
          "payer_device": "ASUS-ROG-Strix",
          "payer_browser": "Chrome 121.0.6167.85",
          "payee_id": "MERCH21000000",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.16
        },
        {
          "transaction_id": "TXN98765432125",
          "transaction_date": "2025-03-17T12:39:27",
          "transaction_amount": 599.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "monica.sinha@gmail.com",
          "payer_mobile": "7123456980",
          "payer_card_brand": null,
          "payer_device": "Samsung M34",
          "payer_browser": null,
          "payee_id": "MERCH10000009",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.02
        },
        {
          "transaction_id": "TXN98765432126",
          "transaction_date": "2025-03-16T18:26:54",
          "transaction_amount": 5299.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "mohan.rao@outlook.com",
          "payer_mobile": "9234567801",
          "payer_card_brand": null,
          "payer_device": "Lenovo-Yoga-7",
          "payer_browser": "Firefox 111.0",
          "payee_id": "MERCH00000098",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.08
        },
        {
          "transaction_id": "TXN98765432127",
          "transaction_date": "2025-03-15T15:42:13",
          "transaction_amount": 1999.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "SBI",
          "payer_email": "kavita.bhatt@gmail.com",
          "payer_mobile": "8345678901",
          "payer_card_brand": "RuPay",
          "payer_device": "OnePlus Nord 3",
          "payer_browser": null,
          "payee_id": "MERCH00000987",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.06
        },
        {
          "transaction_id": "TXN98765432128",
          "transaction_date": "2025-03-17T09:57:36",
          "transaction_amount": 18999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "NEFT",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "arjun.mathur@yahoo.com",
          "payer_mobile": "9678123450",
          "payer_card_brand": null,
          "payer_device": "HP-Spectre-x360",
          "payer_browser": "Chrome 121.0.6167.85",
          "payee_id": "MERCH00009876",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.19
        },
        {
          "transaction_id": "TXN98765432129",
          "transaction_date": "2025-03-16T13:14:29",
          "transaction_amount": 1149.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "tanvi.kapoor@gmail.com",
          "payer_mobile": "9812345607",
          "payer_card_brand": null,
          "payer_device": "Vivo V27 Pro",
          "payer_browser": null,
          "payee_id": "MERCH00098765",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.03
        },
        {
          "transaction_id": "TXN98765432130",
          "transaction_date": "2025-03-15T22:05:47",
          "transaction_amount": 4499.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "ICICI Bank",
          "payer_email": "aditya.roy@hotmail.com",
          "payer_mobile": "7654321890",
          "payer_card_brand": "Visa",
          "payer_device": "Dell-G15",
          "payer_browser": "Edge 112.0.1722.39",
          "payee_id": "MERCH00987654",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.10
        },
        {
          "transaction_id": "TXN98765432131",
          "transaction_date": "2025-03-17T16:23:54",
          "transaction_amount": 799.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Kotak Mahindra Bank",
          "payer_email": "neelam.joshi@gmail.com",
          "payer_mobile": "8976123450",
          "payer_card_brand": null,
          "payer_device": "Xiaomi 12 Pro",
          "payer_browser": null,
          "payee_id": "MERCH09876543",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.04
        },
        {
          "transaction_id": "TXN98765432132",
          "transaction_date": "2025-03-16T11:48:36",
          "transaction_amount": 11999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "Yes Bank",
          "payer_email": "saurabh.mishra@outlook.com",
          "payer_mobile": "9345678012",
          "payer_card_brand": "Mastercard",
          "payer_device": "Lenovo-IdeaPad-5",
          "payer_browser": "Chrome 121.0.6167.85",
          "payee_id": "MERCH98765432",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.13
        },
        {
          "transaction_id": "TXN98765432133",
          "transaction_date": "2025-03-15T17:29:45",
          "transaction_amount": 3799.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "Card",
          "payment_gateway_bank": "SBI",
          "payer_email": "rekha.nair@gmail.com",
          "payer_mobile": "8765432019",
          "payer_card_brand": "RuPay",
          "payer_device": "POCO F5",
          "payer_browser": null,
          "payee_id": "MERCH87654321",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.07
        },
        {
          "transaction_id": "TXN98765432134",
          "transaction_date": "2025-03-17T08:37:19",
          "transaction_amount": 999.00,
          "transaction_channel": "web",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "HDFC Bank",
          "payer_email": "sameer.khan@yahoo.com",
          "payer_mobile": "9812345670",
          "payer_card_brand": null,
          "payer_device": "ASUS-ZenBook-14",
          "payer_browser": "Firefox 111.0",
          "payee_id": "MERCH76543210",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.05
        },
        {
          "transaction_id": "TXN98765432135",
          "transaction_date": "2025-03-16T19:13:28",
          "transaction_amount": 2299.00,
          "transaction_channel": "mobile",
          "transaction_payment_mode": "UPI",
          "payment_gateway_bank": "Axis Bank",
          "payer_email": "shreya.dutta@gmail.com",
          "payer_mobile": "7123459680",
          "payer_card_brand": null,
          "payer_device": "Moto Edge 40",
          "payer_browser": null,
          "payee_id": "MERCH65432109",
          "is_fraud": false,
          "fraud_source": "model",
          "fraud_reason": null,
          "fraud_score": 0.06
        }
    ]
  const systemPrompt = `You are a fraud detection expert. Custom rules are first applied and if it passed then use your learned knowledge from the following examples. Generate no reasoning just the json output. Analyze transaction data and strictly return the following JSON output:
{
  "is_fraud_detected": true/false,
  "fraud_source": "model",
  "fraud_reason": "Brief explanation",
  "fraud_score": 0.0 to 1.0
}

Custom Rules:
${customRules}

Example FRAUD Transactions:
${JSON.stringify(fraudExamples, null, 2)}

Example NONFRAUD TRANSACTIONS: 
${JSON.stringify(nonFraudExamples, null, 2)}
`
  try {
    const response = await client.chat.completions.create({
      model: 'gemini-2.0-flash',
      messages: [
        {
          role: 'system',
          content: systemPrompt
        },
        {
          role: 'user',
          content: JSON.stringify(transactionData)
        }
      ],
      temperature: 0.8,
      max_tokens: 1024,
      response_format: { type: "json_object" }
    })
    
    return JSON.parse(response.choices[0].message.content)
  } catch (error) {
    console.error('Error generating fraud analysis:', error)
    throw error
  }
}